name: "REIO V6 - PROOF OF MATHEMATICAL INVARIANCE (CC EAL7)"

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  verification_formelle:
    name: "Kani Model Checking Verification"
    runs-on: ubuntu-latest
    steps:
      - name: "🔗 Extraction du Code Source REIO"
        uses: actions/checkout@v4

      - name: "🦀 Configuration de la Toolchain Rust Nightly"
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: riscv32imac-unknown-none-elf

      - name: "📦 Installation Manuelle Directe de Kani Verifier"
        run: |
          cargo install --locked kani-verifier
          cargo kani setup

      - name: "⚡ Exécution du Solveur Mathématique sur le Workspace"
        run: |
          cargo kani --workspace --release
